/** Client-side export of a finished inspection.
 *
 *  The report is the actual deliverable of a PROBE run, so it has to leave the
 *  app: Markdown for a ticket or a PR description, JSON for another tool.
 *  Everything here is derived from data the UI already holds — no extra
 *  endpoint, no server round trip.
 */

import type { ReportResponse } from "../types";

import { agentMeta, classificationStyle, severityStyle } from "./format";

function triggerDownload(filename: string, contents: string, mime: string): void {
  const blob = new Blob([contents], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  // Give the click time to be picked up before the object URL disappears.
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function safeSlug(value: string): string {
  return (
    value
      .replace(/^https?:\/\//, "")
      .replace(/[^a-z0-9.]+/gi, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "inspection"
  );
}

/** Markdown rendering of a full report — ready to paste into an issue. */
export function reportToMarkdown(report: ReportResponse): string {
  const lines: string[] = [];

  lines.push(`# PROBE inspection — ${report.application}`);
  lines.push("");
  lines.push(`- **URL:** ${report.url}`);
  lines.push(`- **Depth:** ${report.inspection}`);
  lines.push(`- **Duration:** ${report.duration}`);
  lines.push(`- **Agents:** ${report.agent_count}`);
  lines.push(`- **Browser engine:** ${report.browser}`);
  lines.push(
    `- **Decision engine:** ${report.decision_engine?.mode === "llm" ? `${report.decision_engine.provider} · ${report.decision_engine.model}` : "heuristic policies"}`,
  );
  lines.push(`- **Coverage status:** ${report.complete ? "all agents completed" : "partial — one or more agents failed"}`);
  if (report.generated_at) lines.push(`- **Generated:** ${report.generated_at}`);
  if (report.warnings?.length) {
    lines.push("");
    lines.push("## Run warnings");
    lines.push("");
    for (const warning of report.warnings) lines.push(`- ${warning}`);
  }
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(report.summary || "No summary available.");
  lines.push("");

  lines.push("## Severity breakdown");
  lines.push("");
  lines.push("| Critical | High | Medium | Low | Info |");
  lines.push("| ---: | ---: | ---: | ---: | ---: |");
  lines.push(
    `| ${report.critical} | ${report.high} | ${report.medium} | ${report.low} | ${report.info} |`,
  );
  lines.push("");

  if (report.correlated > 0) {
    lines.push(
      `> ${report.correlated} finding${report.correlated === 1 ? " was" : "s were"} correlated ` +
        "across multiple agent perspectives by the Review AI.",
    );
    lines.push("");
  }

  lines.push("## Findings");
  lines.push("");

  if (report.items.length === 0) {
    lines.push("The agents explored the application and found nothing they could evidence.");
    lines.push("");
  }

  report.items.forEach((finding, index) => {
    const severity = severityStyle(finding.severity);
    const classification = classificationStyle(finding.classification);
    lines.push(`### ${index + 1}. ${finding.title}`);
    lines.push("");
    lines.push(
      `**${severity.label}** · ${classification.label} · ${finding.category} · ` +
        `confidence ${Math.round(finding.confidence * 100)}%` +
        (finding.reproduced ? ` · reproduced ${finding.reproduced}` : "") +
        (finding.correlated ? " · correlated" : ""),
    );
    lines.push("");
    if (finding.url) lines.push(`- **Where:** ${finding.url}`);
    lines.push(`- **Found by:** ${finding.agents.map((role) => agentMeta(role).label).join(", ")}`);
    lines.push("");
    if (finding.description) {
      lines.push(finding.description);
      lines.push("");
    }
    if (finding.expected || finding.actual) {
      lines.push(`- **Expected:** ${finding.expected ?? "—"}`);
      lines.push(`- **Actual:** ${finding.actual ?? "—"}`);
      lines.push("");
    }
    if (finding.steps.length > 0) {
      lines.push("**Reproduction steps**");
      lines.push("");
      finding.steps.forEach((step, stepIndex) => {
        lines.push(`${stepIndex + 1}. \`${step}\``);
      });
      lines.push("");
    }
    if (finding.recommendation) {
      lines.push(`**Recommendation:** ${finding.recommendation}`);
      lines.push("");
    }
  });

  lines.push("## Agents");
  lines.push("");
  lines.push("| Agent | Discoveries | Focus |");
  lines.push("| --- | ---: | --- |");
  for (const agent of report.agents) {
    lines.push(`| ${agent.label} | ${agent.discoveries} | ${agent.goal} |`);
  }
  lines.push("");
  lines.push("---");
  lines.push("_Generated by PROBE — autonomous web application investigation._");
  lines.push("");

  return lines.join("\n");
}

export function exportReportMarkdown(report: ReportResponse): void {
  triggerDownload(
    `probe-${safeSlug(report.application)}.md`,
    reportToMarkdown(report),
    "text/markdown",
  );
}

export function exportReportJson(report: ReportResponse): void {
  triggerDownload(
    `probe-${safeSlug(report.application)}.json`,
    JSON.stringify(report, null, 2),
    "application/json",
  );
}
